### ISSUE TITLE
creating a base16 palette for this theme

### ISSUE THREAD

**Issue by NotAShelf** [JohnOberhauser/Varda-Theme#1]
Hey! 

First and foremost I'd like to tell you how much I appreciate your work on this theme. It is simply brilliant. Really, one of the best themes I've seen on the internet among both meta and non-meta themes.

Long thing short, I would like to generate a base16 theme (and possibly contribute it to the [main base16 repo](https://github.com/tinted-theming/base16-schemes) for other people to be use it) to be used with the [nix-colors](https://github.com/Misterio77/nix-colors) projects so that users may very easily. I would like to hear what you think, and possibly would like to receive your help if you are down.

**Comment by NotAShelf** [comment]
for reference, this is what I could come up with from what you've had in the README

```nix
{ 
      base00 = "#0C0E11"; # Base
      base01 = "#141619"; # Mantle
      base02 = "#2E3436"; # Surface0
      base03 = "#3b4444"; # Surface1
      base04 = "#3b4444"; # Surface2
      base05 = "#E5FFFF"; # text
      base06 = "#E5FFFF"; # "
      base07 = "#D0EBEE"; # white
      base08 = "#D0EBEE"; # "
      base09 = "#733447"; # red
      base0A = "#C78C56"; # yellow
      base0B = "#257B76"; # green
      base0C = "#52677C"; # teal
      base0D = "#52677C"; # blue
      base0E = "#604575"; # magenta
      base0F = "#733447"; # red again
}
 ```

**Comment by JohnOberhauser** [comment]
Hey @NotAShelf 
I only just now saw this.  I think the only change I would make to that list is setting `text` to `#D0EBEE`.  That's what I use for text.  Other than that I think it looks good!

**Comment by NotAShelf** [comment]
Thanks for the response!

I've changed the text color to `#D0EBEE` and it really does look slightly better now. Although, a slight chance had to be made as we don't want the white color to be the equivalent of the text color.

Here's the current - latest- iteration of the palette:

```nix
# in nix because I primarly use this palette with nix-colors
{
  colorscheme = {
    slug = "varda-theme";
    name = "Varda Theme";
    kind = "dark";
    colors = {
      base00 = "#0C0E11"; # Base
      base01 = "#141619"; # Mantle
      base02 = "#2E3436"; # Surface0
      base03 = "#3b4444"; # Surface1
      base04 = "#3b4444"; # Surface2
      base05 = "#D0EBEE"; # text
      base06 = "#D0EBEE"; # "
      base07 = "#E5FFFF"; # white
      base08 = "#E5FFFF"; # "
      base09 = "#733447"; # red
      base0A = "#C78C56"; # yellow
      base0B = "#257B76"; # green
      base0C = "#52677C"; # teal
      base0D = "#52677C"; # blue
      base0E = "#604575"; # magenta
      base0F = "#733447"; # red again
    };
  };
}
```
